name: WindowsVM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Start Windows VM
        run: |
          echo Windows VM started
          ipconfig
          ping -n 21600 127.0.0.1 > nul
